### ISSUE TITLE
Role="button" on a button is unnecessary

### ISSUE THREAD

**Issue by scottaohara** [felixgirault/rea11y#7]
Hi there,

Looking through your components today and noticed you are using a ```role="button"``` on your (button component)[https://github.com/felixgirault/rea11y/blob/master/src/Button.js].

This is typically discouraged as it's a redundant declaration to the inherent semantics of the button element.

What would be nice to see on this component though, and would be the appropriate way to make sure that buttons don't default to 'submit' when used in a form, would be a default ```type="button"``` applied to the button, with an option to update the type value to ```submit``` or ```reset``` on an as-needed basis.

Thanks!

**Comment by felixgirault** [comment]
Hi,
messed
You're totally right :) 
I think that is what I wanted to do, but I confused `role` with `type`.

Anyway, thank you for noticing! I'll fix that soon.

**Comment by felixgirault** [comment]
This should be ok now https://github.com/felixgirault/rea11y/commit/162f7c337fa8f6d6fc5011013c515fcb701b26f3
